<?php defined('SMSPanel') or die('Snooping around is not allowed. Please use the front door');
$sconfig['host'] = '197.50.53.109';
$sconfig['database'] = 'admin_smsmsms';
$sconfig['user'] = 'admin_smsmsms';
$sconfig['password'] = 'smsmsms';
$sconfig['server'] = 'Server_Name';
$sconfig['Appkey'] = '$P$B3e0dLgeYgB33fVgcL0AnkWF4vvuhb/';
$sconfig['cache_on'] = FALSE;
$sconfig['cachedir'] = 'CACH_DIR';
$sconfig['char_set'] = 'utf8';
$sconfig['installed'] = 'INSTALLED';
$sconfig['verssion_id'] = '25';
$sconfig['Server_HTTP_State'] = '54236733';
$sconfig['dbcollat'] = 'utf8_general_ci';
$sconfig['swap_pre'] = ''; //
$sconfig['app_version'] = '5.0.0';
$sconfig['app_name'] = 'Sendroid SMS Portal';
$sconfig['version_date'] = '2016-10-10';
$sconfig['autoinit'] = TRUE;
$sconfig['stricton'] = FALSE;
?>